# Configuration for PR labeler
# Labels PRs based on changed files

# Documentation
docs:
  - changed-files:
    - any-glob-to-any-file: ['docs/**', '*.md', 'README*']

# Tests
tests:
  - changed-files:
    - any-glob-to-any-file: ['test/**', '**/*_test.dart']

# Flutter/Dart code
code:
  - changed-files:
    - any-glob-to-any-file: ['lib/**/*.dart']

# Configuration files
config:
  - changed-files:
    - any-glob-to-any-file: ['pubspec.yaml', 'analysis_options.yaml', '.github/**']

# UI/Theme
ui:
  - changed-files:
    - any-glob-to-any-file: ['lib/theme/**', 'lib/screens/**', 'lib/widgets/**']

# Backend/Services
backend:
  - changed-files:
    - any-glob-to-any-file: ['lib/services/**', 'lib/models/**', 'supabase/**']

# CI/CD
ci-cd:
  - changed-files:
    - any-glob-to-any-file: ['.github/workflows/**']

# Dependencies
dependencies:
  - changed-files:
    - any-glob-to-any-file: ['pubspec.yaml', 'pubspec.lock']

# Android
android:
  - changed-files:
    - any-glob-to-any-file: ['android/**']

# iOS
ios:
  - changed-files:
    - any-glob-to-any-file: ['ios/**']

# Web
web:
  - changed-files:
    - any-glob-to-any-file: ['web/**']
